version: '3.9'

services:
  dev:
    container_name: nestjs_api_dev
    image: nestjs-api-dev:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: npm run start:debug
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: "postgres"
  postgres:
    image: postgres:latest
    restart: always
    command: ["postgres", "-c", "log_statement=all"]
    ports:
      - "127.0.0.1:5433:5432"
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cards
